apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: testdb
  name: testdb
spec:
  template:
    spec:
      containers:
      - name: testdb
        env:
        - name: MYSQL_AIO
          value: "0"
        - name: MYSQL_DATABASE
          value: testdb
        - name: MYSQL_PASSWORD
          value: redhat
        - name: MYSQL_USER
          value: test
