MYSQL_DB_NAME=testdb
MYSQL_DB_PORT=3306
MYSQL_DB_USERNAME=test
MYSQL_DB_PASSWORD=redhat
MYSQL_DB_HOST=ac0f1a19cfcc04906b5a2d3ef8d8d332-1663157015.us-east-2.elb.amazonaws.com

APP_NAME=tee-tools

oc delete deploy $APP_NAME
oc delete svc $APP_NAME
oc delete route $APP_NAME

oc new-app tee-tools -e OPENSHIFT_MYSQL_DB_HOST=$MYSQL_DB_HOST -e OPENSHIFT_MYSQL_DB_NAME=$MYSQL_DB_NAME -e OPENSHIFT_MYSQL_DB_PORT=$MYSQL_DB_PORT -e OPENSHIFT_MYSQL_DB_USERNAME=$MYSQL_DB_USERNAME -e OPENSHIFT_MYSQL_DB_PASSWORD=$MYSQL_DB_PASSWORD

oc expose svc $APP_NAME
