apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: testdb
  name: testdb
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    deploymentconfig: testdb
  strategy:
    activeDeadlineSeconds: 21600
    recreateParams:
      timeoutSeconds: 600
    resources: {}
    type: Recreate
  template:
    metadata:
      labels:
        deploymentconfig: testdb
    spec:
      containers:
      - env:
        - name: MYSQL_AIO
          value: "0"
        - name: MYSQL_DATABASE
          value: testdb
        - name: MYSQL_PASSWORD
          value: redhat
        - name: MYSQL_USER
          value: test
        image: registry.redhat.io/rhel8/mysql-80:latest
        imagePullPolicy: Always
        name: testdb
        ports:
        - containerPort: 3306
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: volume-mdbbm
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: volume-mdbbm
        persistentVolumeClaim:
          claimName: testdb-data
status: {}
