apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: testdb-data
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5G
  storageClassName: gp2
  volumeMode: Filesystem
status: {}

