apiVersion: v1
kind: Service
metadata:
  labels:
    app: tee-tools
  name: tee-tools
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    deployment: tee-tools
  sessionAffinity: None
  type: ClusterIP
status: {}

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: testdb
  name: testdb
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  ports:
  - name: 3306-tcp
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    deployment: testdb
  sessionAffinity: None
  type: ClusterIP
status: {}

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: testdb
  name: testdb-lb-service
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  ports:
  - nodePort: 30232
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    deployment: testdb
  sessionAffinity: None
  type: LoadBalancer
status: {}

