apiVersion: v1
data:
  initial-database.sh: |
    mysql -h $MYSQL_HOST -u$MYSQL_USER -p$MYSQL_PASSWORD -P3306 $MYSQL_DATABASE <<EOF
    CREATE TABLE IF NOT EXISTS users (
    user_id int(10) unsigned NOT NULL AUTO_INCREMENT,
    name varchar(100) NOT NULL,
    email varchar(100) NOT NULL,
    PRIMARY KEY (user_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
    insert into users(name,email) values ('user1', 'user1@example.com');
    insert into users(name,email) values ('user2', 'user2@example.com');
    insert into users(name,email) values ('user3', 'user3@example.com');
    EOF
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: testdb-configmap
  annotations:
    argocd.argoproj.io/sync-wave: "0"
