apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    app: testdb
  name: testdb
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      deployment: testdb
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      creationTimestamp: null
      labels:
        deployment: testdb
    spec:
      containers:
      - env:
        - name: MYSQL_AIO
          value: "0"
        - name: MYSQL_DATABASE
          value: testdb
        - name: MYSQL_PASSWORD
          value: redhat
        - name: MYSQL_USER
          value: test
        image: registry.redhat.io/rhel8/mysql-80:latest
        imagePullPolicy: IfNotPresent
        name: testdb
        ports:
        - containerPort: 3306
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: volume-tkq7s
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: volume-tkq7s
        persistentVolumeClaim:
          claimName: testdb-data
status: {}
